version: "3.9"
services:
  api:
    build:
      context: ./api
    container_name: ai-agent-api
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app

  ui:
    build:
      context: ./ui
    container_name: ai-agent-ui
    depends_on:
      - api
    ports:
      - "8501:8501"
    env_file:
      - ./ui/.env
    volumes:
      - ./ui:/app